<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(

	'alembic (laboratory set)' => $set . '_f100',
	'alembic-1 (laboratory set)' => $set . '_f101',
	'alien (laboratory set)' => $set . '_f102',
	'asteroid (laboratory set)' => $set . '_f103',
	'atomic-symbol (laboratory set)' => $set . '_f104',
	'atoms (laboratory set)' => $set . '_f105',
	'bacteria (laboratory set)' => $set . '_f106',
	'bacteria-and-loupe (laboratory set)' => $set . '_f107',
	'big-flask (laboratory set)' => $set . '_f108',
	'big-planet (laboratory set)' => $set . '_f109',
	'big-syringe (laboratory set)' => $set . '_f10a',
	'bowl (laboratory set)' => $set . '_f10b',
	'chemical-composition (laboratory set)' => $set . '_f10c',
	'cooking-flask (laboratory set)' => $set . '_f10d',
	'dna (laboratory set)' => $set . '_f10e',
	'dna-1 (laboratory set)' => $set . '_f10f',
	'dropper (laboratory set)' => $set . '_f110',
	'earth-globe (laboratory set)' => $set . '_f111',
	'exchanging-chemicals (laboratory set)' => $set . '_f112',
	'experiment-results (laboratory set)' => $set . '_f113',
	'explosion (laboratory set)' => $set . '_f114',
	'flame (laboratory set)' => $set . '_f115',
	'flask (laboratory set)' => $set . '_f116',
	'flask-with-label (laboratory set)' => $set . '_f117',
	'galaxy (laboratory set)' => $set . '_f118',
	'germ-sample (laboratory set)' => $set . '_f119',
	'human-mind (laboratory set)' => $set . '_f11a',
	'laboratory-certificate (laboratory set)' => $set . '_f11b',
	'light-bulb (laboratory set)' => $set . '_f11c',
	'microscope (laboratory set)' => $set . '_f11d',
	'observatory (laboratory set)' => $set . '_f11e',
	'open-science-book (laboratory set)' => $set . '_f11f',
	'pill-jar (laboratory set)' => $set . '_f120',
	'planet-and-moons (laboratory set)' => $set . '_f121',
	'safety-glasses (laboratory set)' => $set . '_f122',
	'satellite (laboratory set)' => $set . '_f123',
	'satellite-1 (laboratory set)' => $set . '_f124',
	'science-book (laboratory set)' => $set . '_f125',
	'scientific-data (laboratory set)' => $set . '_f126',
	'solar-system (laboratory set)' => $set . '_f127',
	'still (laboratory set)' => $set . '_f128',
	'still-with-liquid (laboratory set)' => $set . '_f129',
	'syringe (laboratory set)' => $set . '_f12a',
	'telescope (laboratory set)' => $set . '_f12b',
	'test-tubes (laboratory set)' => $set . '_f12c',
	'test-tubes-1 (laboratory set)' => $set . '_f12d',
	'thermometer (laboratory set)' => $set . '_f12e',
	'thermometer-1 (laboratory set)' => $set . '_f12f',
	'two-test-tubes (laboratory set)' => $set . '_f130',
	'ufo (laboratory set)' => $set . '_f131'
);