<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(

	'dna (molecular set)' => $set . '_f100',
	'atom (molecular set)' => $set . '_f101',
	'bacteria (molecular set)' => $set . '_f102',
	'molecular (molecular set)' => $set . '_f103',
	'flask (molecular set)' => $set . '_f104',
	'flask (molecular set)' => $set . '_f105',
	'flask (molecular set)' => $set . '_f106',
	'book (molecular set)' => $set . '_f107',
	'file (molecular set)' => $set . '_f108',
	'grinding (molecular set)' => $set . '_f109',
	'dangerous (molecular set)' => $set . '_f10a',
	'biohazard (molecular set)' => $set . '_f10b',
	'research (molecular set)' => $set . '_f10c',
	'test-tubes (molecular set)' => $set . '_f10d',
	'microscope (molecular set)' => $set . '_f10e',
	'scalpel (molecular set)' => $set . '_f10f',
	'beaker (molecular set)' => $set . '_f110',
	'wash-bottle (molecular set)' => $set . '_f111',
	'wire-gauze (molecular set)' => $set . '_f112',
	'glass (molecular set)' => $set . '_f113',
	'scale (molecular set)' => $set . '_f114',
	'bunsen-burner (molecular set)' => $set . '_f115',
	'dropper (molecular set)' => $set . '_f116',
	'thermometer (molecular set)' => $set . '_f117',
	'pan (molecular set)' => $set . '_f118',
	'molecular (molecular set)' => $set . '_f119',
	'separating-funnel (molecular set)' => $set . '_f11a',
	'flask (molecular set)' => $set . '_f11b',
	'gmo-food (molecular set)' => $set . '_f11c',
	'rat (molecular set)' => $set . '_f11d',
	'document (molecular set)' => $set . '_f11e',
	'research (molecular set)' => $set . '_f11f',
	'test-tubes (molecular set)' => $set . '_f120',
	'experiment (molecular set)' => $set . '_f121',
	'dead (molecular set)' => $set . '_f122',
	'chemical-substances (molecular set)' => $set . '_f123',
	'doctor-coat (molecular set)' => $set . '_f124',
	'injection (molecular set)' => $set . '_f125',
	'chemical-reaction (molecular set)' => $set . '_f126',
	'radiation (molecular set)' => $set . '_f127',
	'cylinder (molecular set)' => $set . '_f128',
	'funnel (molecular set)' => $set . '_f129',
	'corrosive (molecular set)' => $set . '_f12a',
	'oxidant (molecular set)' => $set . '_f12b',
	'flasks (molecular set)' => $set . '_f12c',
	'uranium (molecular set)' => $set . '_f12d',
	'hydrogen (molecular set)' => $set . '_f12e',
	'glasses (molecular set)' => $set . '_f12f',
	'test-tube (molecular set)' => $set . '_f130',
	'tank (molecular set)' => $set . '_f131'
);