<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(

	'periodic-table (chemistry set)' => $set . '_f100',
	'molecule (chemistry set)' => $set . '_f101',
	'flask (chemistry set)' => $set . '_f102',
	'bacteria (chemistry set)' => $set . '_f103',
	'atom (chemistry set)' => $set . '_f104',
	'chemical-reaction (chemistry set)' => $set . '_f105',
	'dropper (chemistry set)' => $set . '_f106',
	'poison (chemistry set)' => $set . '_f107',
	'dna (chemistry set)' => $set . '_f108',
	'beakers (chemistry set)' => $set . '_f109',
	'petri-dish (chemistry set)' => $set . '_f10a',
	'experiment (chemistry set)' => $set . '_f10b',
	'microscope (chemistry set)' => $set . '_f10c',
	'glasses (chemistry set)' => $set . '_f10d',
	'test-tubes (chemistry set)' => $set . '_f10e',
	'nuclear (chemistry set)' => $set . '_f10f',
	'nuclear (chemistry set)' => $set . '_f110',
	'mortar (chemistry set)' => $set . '_f111',
	'flask (chemistry set)' => $set . '_f112',
	'beaker (chemistry set)' => $set . '_f113',
	'mouse (chemistry set)' => $set . '_f114',
	'hazard (chemistry set)' => $set . '_f115',
	'gloves (chemistry set)' => $set . '_f116',
	'scientist (chemistry set)' => $set . '_f117',
	'pills (chemistry set)' => $set . '_f118',
	'scale (chemistry set)' => $set . '_f119',
	'bunsen-burner (chemistry set)' => $set . '_f11a',
	'waste (chemistry set)' => $set . '_f11b',
	'report (chemistry set)' => $set . '_f11c',
	'research (chemistry set)' => $set . '_f11d',
	'syringe (chemistry set)' => $set . '_f11e',
	'cell (chemistry set)' => $set . '_f11f',
	'science-book (chemistry set)' => $set . '_f120',
	'experiment (chemistry set)' => $set . '_f121',
	'pendulum (chemistry set)' => $set . '_f122',
	'bunsen-burner (chemistry set)' => $set . '_f123',
	'atom (chemistry set)' => $set . '_f124',
	'magnet (chemistry set)' => $set . '_f125',
	'lab-coat (chemistry set)' => $set . '_f126',
	'factory (chemistry set)' => $set . '_f127',
	'paper (chemistry set)' => $set . '_f128',
	'molecule (chemistry set)' => $set . '_f129',
	'medicine (chemistry set)' => $set . '_f12a',
	'research (chemistry set)' => $set . '_f12b',
	'fire (chemistry set)' => $set . '_f12c',
	'notepad (chemistry set)' => $set . '_f12d',
	'battery-status (chemistry set)' => $set . '_f12e',
	'ph-meter (chemistry set)' => $set . '_f12f',
	'skull (chemistry set)' => $set . '_f130',
	'tube (chemistry set)' => $set . '_f131'
);