<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(

	'test-6 (test set)' => $set . '_f100',
	'test-5 (test set)' => $set . '_f101',
	'test-4 (test set)' => $set . '_f102',
	'review-1 (test set)' => $set . '_f103',
	'balance (test set)' => $set . '_f104',
	'bug (test set)' => $set . '_f105',
	'analytics (test set)' => $set . '_f106',
	'rating (test set)' => $set . '_f107',
	'envelope (test set)' => $set . '_f108',
	'chat (test set)' => $set . '_f109',
	'review (test set)' => $set . '_f10a',
	'test-3 (test set)' => $set . '_f10b',
	'microscope (test set)' => $set . '_f10c',
	'blood-test-1 (test set)' => $set . '_f10d',
	'question (test set)' => $set . '_f10e',
	'package (test set)' => $set . '_f10f',
	'blood-test (test set)' => $set . '_f110',
	'fail (test set)' => $set . '_f111',
	'check-2 (test set)' => $set . '_f112',
	'testing-glasses (test set)' => $set . '_f113',
	'test-2 (test set)' => $set . '_f114',
	'mouse (test set)' => $set . '_f115',
	'flask (test set)' => $set . '_f116',
	'test-tube (test set)' => $set . '_f117',
	'check-1 (test set)' => $set . '_f118',
	'test-1 (test set)' => $set . '_f119',
	'test (test set)' => $set . '_f11a',
	'smartphone-1 (test set)' => $set . '_f11b',
	'speed (test set)' => $set . '_f11c',
	'presentation (test set)' => $set . '_f11d',
	'smartphone (test set)' => $set . '_f11e',
	'computer (test set)' => $set . '_f11f',
	'laptop (test set)' => $set . '_f120',
	'cancel (test set)' => $set . '_f121',
	'check (test set)' => $set . '_f122',
	'stopwatch (test set)' => $set . '_f123',
	'browser (test set)' => $set . '_f124',
	'testing (test set)' => $set . '_f125',
	'barcode (test set)' => $set . '_f126',
	'clipboard (test set)' => $set . '_f127'
);