<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(

	'alien-head (study set)' => $set . '_f100',
	'assistant (study set)' => $set . '_f101',
	'atom (study set)' => $set . '_f102',
	'atom-1 (study set)' => $set . '_f103',
	'board (study set)' => $set . '_f104',
	'brain (study set)' => $set . '_f105',
	'bulb-on-fire (study set)' => $set . '_f106',
	'calculator (study set)' => $set . '_f107',
	'cardiogram (study set)' => $set . '_f108',
	'compass (study set)' => $set . '_f109',
	'dividers (study set)' => $set . '_f10a',
	'dna (study set)' => $set . '_f10b',
	'dna-1 (study set)' => $set . '_f10c',
	'earth-globe (study set)' => $set . '_f10d',
	'electron (study set)' => $set . '_f10e',
	'flask (study set)' => $set . '_f10f',
	'gears (study set)' => $set . '_f110',
	'germs (study set)' => $set . '_f111',
	'glasses (study set)' => $set . '_f112',
	'gloves (study set)' => $set . '_f113',
	'light-bulb (study set)' => $set . '_f114',
	'loupe (study set)' => $set . '_f115',
	'magnet (study set)' => $set . '_f116',
	'measurer (study set)' => $set . '_f117',
	'microscope (study set)' => $set . '_f118',
	'molecule (study set)' => $set . '_f119',
	'molecule-1 (study set)' => $set . '_f11a',
	'molecule-2 (study set)' => $set . '_f11b',
	'monitor-with-stats (study set)' => $set . '_f11c',
	'monkey (study set)' => $set . '_f11d',
	'newton-cradle (study set)' => $set . '_f11e',
	'observatory (study set)' => $set . '_f11f',
	'pipette (study set)' => $set . '_f120',
	'pulse (study set)' => $set . '_f121',
	'radar (study set)' => $set . '_f122',
	'radiation (study set)' => $set . '_f123',
	'rat (study set)' => $set . '_f124',
	'report (study set)' => $set . '_f125',
	'satellite (study set)' => $set . '_f126',
	'saturn (study set)' => $set . '_f127',
	'science-book (study set)' => $set . '_f128',
	'scientist (study set)' => $set . '_f129',
	'scientist-1 (study set)' => $set . '_f12a',
	'scientist-woman (study set)' => $set . '_f12b',
	'syringe (study set)' => $set . '_f12c',
	'telescope (study set)' => $set . '_f12d',
	'thermometer (study set)' => $set . '_f12e',
	'three-test-tubes (study set)' => $set . '_f12f',
	'virus (study set)' => $set . '_f130',
	'water (study set)' => $set . '_f131'
);